### ISSUE TITLE
Pocketbase

### ISSUE THREAD

**Issue by Solear** [doen1el/komoot-to-wanderer#3]
Hi! Great idea!
I'm not sure why its not working for me.
I think its because a pocketbase-url. Which url it is? The same like wanderer? Do I need a port?

services:
  komoot-to-wanderer:
    image: komoot-to-wanderer
    container_name: komoot-to-wanderer
    restart: unless-stopped
    environment:
      - WANDERER_BASE_URL=http://192.168.1.35
      - WANDERER_EMAIL=a@b.de
      - WANDERER_PASSWORD=xxx
      - KOMOOT_EMAIL=b@a.de
      - KOMOOT_PASSWORD=xxx
      - POCKETBASE_BASE_URL=http://192.168.1.35
      - SCHEDULE_TIME=00:30:00 # e.g. every day at 00:30

**Comment by doen1el** [comment]
Hi, did you install wanderer using the `docker-compose.yml` file? If so, you can find the port here:
```
db:
    container_name: wanderer-db
    image: flomp/wanderer-db
    depends_on:
      search:
        condition: service_healthy
    environment:
      <<: *cenv
    ports:
      - "8090:8090"
```

Your IP would be the IP of your PC/server. Something like 192.168.0.xxx. 
So your `POCKETBASE_BASE_URL` would be `192.168.0.xxx:8090`.

Your `WANDERER_BASE_URL` also need a PORT. You can also find it in the `docker-compose.yml` from wanderer.
